qpid::framing Namespace Reference
Apache Qpid - AMQP Messaging for Java JMS, C++, Python, Ruby, and .NET Apache Qpid Documentation
qpid::framing Namespace Reference
The framing namespace contains classes that are used to create, send and receive the basic packets from which AMQP is built.
Classes
class Array
struct OutOfBounds
class Buffer
class FieldTable
A set of name-value pairs.
class FieldValueException
Exception that is the base exception for all field table errors.
struct InvalidConversionException
Exception thrown when we can't perform requested conversion.
class FieldValue
Value that can appear in an AMQP field table.
class FixedWidthValue
class FixedWidthValue< 0 >
class VariableWidthValue
class EncodedValue
class Str8Value
class Str16Value
class Var16Value
class Var32Value
class Struct32Value
class FloatValue
class DoubleValue
class IntegerValue
class TimeValue
class Integer64Value
class Unsigned64Value
class FieldTableValue
class ArrayValue
class VoidValue
class BoolValue
class Unsigned8Value
class Unsigned16Value
class Unsigned32Value
class Integer8Value
class Integer16Value
class ListValue
class UuidValue
class List
Representation of an AMQP 0-10 list.
class ProtocolVersion
class SequenceNumber
4-byte sequence number that 'wraps around'.
struct Window
class SequenceSet
class StructHelper
struct Uuid
A UUID is represented as a boost::array of 16 bytes.
Typedefs
typedef uint8_t FrameType
typedef uint16_t ChannelId
typedef uint32_t BatchOffset
typedef uint8_t ClassId
typedef uint8_t MethodId
typedef uint16_t ReplyCode
typedef IntegerValue Integer32Value
Enumerations
enum DeliveryMode { TRANSIENT = 1, PERSISTENT = 2 }
Functions
std::ostream & operator<< (std::ostream &, const Buffer &)
template<>
bool FieldValue::convertsTo< std::string > () const
template<>
std::string FieldValue::get< std::string > () const
std::ostream & operator<< (std::ostream &out, const FieldValue &v)
template<class T >
bool getEncodedValue (FieldTable::ValuePtr vptr, T &value)
int32_t operator- (const SequenceNumber &a, const SequenceNumber &b)
SequenceNumber operator+ (const SequenceNumber &a, int32_t n)
SequenceNumber operator- (const SequenceNumber &a, int32_t n)
std::ostream & operator<< (std::ostream &o, const SequenceNumber &n)
std::ostream & operator<< (std::ostream &, Uuid)
Print in format 1b4e28ba-2fa1-11d2-883f-b9a761bde3fb.
std::istream & operator>> (std::istream &, Uuid &)
Read from format 1b4e28ba-2fa1-11d2-883f-b9a761bde3fb.
Variables
const ChannelId CHANNEL_MAX = (ChannelId(~1))>>1
Maximum channel ID used by broker.
const ChannelId CHANNEL_HIGH_BIT = ChannelId(~CHANNEL_MAX)
Detailed Description
The framing namespace contains classes that are used to create, send and receive the basic packets from which AMQP is built.
Typedef Documentation
typedef uint32_t qpid::framing::BatchOffset
Definition at line 36 of file amqp_types.h.
typedef uint16_t qpid::framing::ChannelId
Definition at line 35 of file amqp_types.h.
typedef uint8_t qpid::framing::ClassId
Definition at line 37 of file amqp_types.h.
typedef uint8_t qpid::framing::FrameType
Definition at line 34 of file amqp_types.h.
typedef IntegerValue qpid::framing::Integer32Value
Definition at line 446 of file FieldValue.h.
typedef uint8_t qpid::framing::MethodId
Definition at line 38 of file amqp_types.h.
typedef uint16_t qpid::framing::ReplyCode
Definition at line 39 of file amqp_types.h.
Enumeration Type Documentation
enum qpid::framing::DeliveryMode
Enumerator:
TRANSIENT
PERSISTENT
Definition at line 61 of file amqp_types.h.
Function Documentation
template<> bool qpid::framing::FieldValue::convertsTo< std::string > () const [inline]
Definition at line 124 of file FieldValue.h.
template<> std::string qpid::framing::FieldValue::get< std::string > () const [inline]
Definition at line 133 of file FieldValue.h.
template<class T > bool qpid::framing::getEncodedValue (FieldTable::ValuePtr vptr, T & value)
Definition at line 460 of file FieldValue.h.
SequenceNumber qpid::framing::operator+ (const SequenceNumber & a, int32_t n) [inline]
Definition at line 66 of file SequenceNumber.h.
References qpid::framing::SequenceNumber::getValue().
int32_t qpid::framing::operator- (const SequenceNumber & a, const SequenceNumber & b) [inline]
Definition at line 62 of file SequenceNumber.h.
References qpid::framing::SequenceNumber::getValue().
SequenceNumber qpid::framing::operator- (const SequenceNumber & a, int32_t n) [inline]
Definition at line 70 of file SequenceNumber.h.
References qpid::framing::SequenceNumber::getValue().
std::ostream& qpid::framing::operator<< (std::ostream & o, const SequenceNumber & n)
std::ostream& qpid::framing::operator<< (std::ostream & , Uuid)
Print in format 1b4e28ba-2fa1-11d2-883f-b9a761bde3fb.
std::ostream& qpid::framing::operator<< (std::ostream & , const Buffer &)
std::ostream& qpid::framing::operator<< (std::ostream & out, const FieldValue & v) [inline]
Definition at line 135 of file FieldValue.h.
References qpid::framing::FieldValue::print().
std::istream& qpid::framing::operator>> (std::istream & , Uuid &)
Read from format 1b4e28ba-2fa1-11d2-883f-b9a761bde3fb.
Variable Documentation
const ChannelId qpid::framing::CHANNEL_HIGH_BIT = ChannelId(~CHANNEL_MAX)
Definition at line 51 of file amqp_types.h.
const ChannelId qpid::framing::CHANNEL_MAX = (ChannelId(~1))>>1
Maximum channel ID used by broker.
Reserve high bit for internal use.
Definition at line 50 of file amqp_types.h.
Qpid C++ API Reference