#!/usr/bin/python
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

from transom.script import *

doxygen_conf_template = u"""
DISABLE_INDEX = yes
EXTRACT_ALL = yes
GENERATE_LATEX = no
GENERATE_TREEVIEW = yes
HAVE_DOT = yes
PROJECT_NUMBER = {release}
QUIET = yes
RECURSIVE = yes
INPUT = {input_paths}
PROJECT_NAME = "{title}"
STRIP_FROM_PATH = {strip_paths}
HTML_OUTPUT = {output_dir}
"""

def gen_doxygen(release, title, input_paths, strip_paths, output_dir):
    input_paths = " ".join(input_paths)
    strip_paths = " ".join(strip_paths)

    make_dirs(output_dir)

    conf = doxygen_conf_template.format(**locals())
    path = write_entry("conf", conf)

    call("doxygen {}", path)

    touch(join(output_dir, ".transom-skip"))

def gen_epydoc(release, title, input_paths, input_namespaces, output_dir):
    # XXX programmatic instead?

    input_paths = ":".join(input_paths)
    input_namespaces = " ".join(input_namespaces)

    make_dirs(output_dir)

    options = list()
    options.append("--graph all")
    options.append("--html")
    options.append("--name \"{}\"".format(title))
    options.append("--no-private")
    options.append("--output {}".format(output_dir))
    options.append("--quiet")
    options.append("--url \"@site-url@/index.html\"")
    options = " ".join(options)

    call("PYTHONPATH={} epydoc {} {}", input_paths, options, input_namespaces)

    touch(join(output_dir, ".transom-skip"))

def gen_rdoc(release, title, base_input_path, input_paths, output_dir):
    output_dir = os.path.abspath(output_dir)

    # rdoc really wants to make the last dir
    make_dirs(split(output_dir)[0])

    options = list()
    options.append("--fmt html")
    options.append("--op {}".format(output_dir))
    options.append("--quiet")
    options.append("--title \"{}\"".format(title))
    options = " ".join(options)

    input_paths = " ".join(input_paths)

    call("cd {} && rdoc {} {}", base_input_path, options, input_paths)
    
    touch(join(output_dir, ".transom-skip"))

def gen_messaging_api(release, source_dir, release_dir):
    component_dir = join(release_dir, "messaging-api")
    remove(component_dir)

    gen_cpp_messaging_api(release, source_dir, component_dir)
    gen_dotnet_messaging_api(release, source_dir, component_dir)
    gen_python_messaging_api(release, source_dir, component_dir)
    gen_ruby_messaging_api(release, source_dir, component_dir)

def gen_cpp_messaging_api(release, source_dir, component_dir):
    include_dir = join(source_dir, "cpp", "include")
    input_paths = (
        join(source_dir, "cpp", "docs", "api", "doxygen_mainpage.h"),
        join(include_dir, "qpid", "messaging"),
        join(include_dir, "qpid", "types"),
        )
    output_dir = join(component_dir, "cpp", "api")

    gen_doxygen(release=release,
                title="Qpid C++ Messaging API",
                input_paths=input_paths,
                strip_paths=(include_dir,),
                output_dir=output_dir)

def gen_dotnet_messaging_api(release, source_dir, component_dir):
    include_dir = join(source_dir, "cpp", "bindings", "qpid", "dotnet", "src")
    input_paths = (include_dir,)
    output_dir = join(component_dir, "dotnet", "api")

    gen_doxygen(release=release,
                title="Qpid .NET Messaging API",
                input_paths=input_paths,
                strip_paths=(include_dir,),
                output_dir=output_dir)

def gen_python_messaging_api(release, source_dir, component_dir):
    input_path = join(source_dir, "python")
    input_namespace = "qpid.messaging"
    output_dir = join(component_dir, "python", "api")

    gen_epydoc(release=release,
               title="Qpid Python Messaging API",
               input_paths=(input_path,),
               input_namespaces=(input_namespace,),
               output_dir=output_dir)

def gen_ruby_messaging_api(release, source_dir, component_dir):
    base_input_path = join(source_dir, "cpp", "bindings")
    input_path = join("qpid", "ruby", "lib")
    output_dir = join(component_dir, "ruby", "api")

    gen_rdoc(release=release,
             title="Qpid Ruby Messaging API",
             base_input_path=base_input_path,
             input_paths=(input_path,),
             output_dir=output_dir)

    #name = "qpid-{}-ruby-messaging-api-apiref".format(release)
    #make_archive(api_dir, output_dir, name)

## Now do stuff ##

if len(sys.argv) != 3:
    sys.exit("Usage: script RELEASE RELEASE-DIR")

call("dot -V")
call("doxygen --version")
call("epydoc --version")
call("rdoc --version")

release = sys.argv[1]
release_dir = sys.argv[2]
source_dir = export_release(release)

gen_messaging_api(release, source_dir, release_dir)
