#!/usr/bin/python
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

from transom.generate import *

template = \
"""
;;
;; Licensed to the Apache Software Foundation (ASF) under one
;; or more contributor license agreements.  See the NOTICE file
;; distributed with this work for additional information
;; regarding copyright ownership.  The ASF licenses this file
;; to you under the Apache License, Version 2.0 (the
;; "License"); you may not use this file except in compliance
;; with the License.  You may obtain a copy of the License at
;; 
;;   http://www.apache.org/licenses/LICENSE-2.0
;; 
;; Unless required by applicable law or agreed to in writing,
;; software distributed under the License is distributed on an
;; "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
;; KIND, either express or implied.  See the License for the
;; specific language governing permissions and limitations
;; under the License.
;;

# Jiropticon

## Completed features and improvements by component

{completed_features}

## Requested features and improvements by component

{requested_features}

## Open bugs by component

{open_bugs}
"""

def gen_jiropticon(output_path):
    query = QpidQuery()
    query.add("issuetype", "in", """("New Feature", "Improvement")""")
    query.add("status", "in", """("Closed", "Resolved")""")
    query.add("resolution", "=", "Fixed")

    completed_features = render_component_list(query)

    query = QpidQuery()
    query.add("issuetype", "in", """("New Feature", "Improvement")""")
    query.add("status", "in",
              """("Open", "Reopened", "In Progress", "Ready To Review")""")

    requested_features = render_component_list(query)

    query = QpidQuery()

    query.add("issuetype", "=", "Bug")
    query.add("status", "in",
              """("Open", "Reopened", "In Progress", "Ready To Review")""")

    open_bugs = render_component_list(query)

    output = template.format(**locals())
    output = output.strip()

    write(output_path, output)

def render_component_list(query):
    lines = list()

    for component in query.components:
        copy = query.copy()
        copy.add("component", "=", component)
        href = copy.render()
        lines.append(" - [{}]({})".format(component, href))

    return "\n".join(lines)

if len(sys.argv) != 2:
    sys.exit("Usage: script OUTPUT-PATH")

output_path = sys.argv[1]

gen_jiropticon(output_path)
