#!/usr/bin/python
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

import sys, os, urllib, string

version = sys.argv[1]

download_records = (
    ("qpid-proton-{}.tar.gz", "AMQP Messenger, AMQP Protocol Engine"),
    )

download_rows = list()

for artifact, summary in download_records:
    artifact = artifact.format(version)
    artifact_url = "http://www.apache.org/dyn/closer.cgi/qpid/proton/{}/{}".format(version, artifact)
    sig_url = "http://www.apache.org/dist/qpid/proton/{}/{}.asc".format(version, artifact)

    args = summary, artifact, artifact_url, sig_url
    row = "|| {} || [{}]({}) || [PGP]({}) ||".format(*args)

    download_rows.append(row)

downloads = "\n  ".join(download_rows)

component_records = (
    ("messenger", "AMQP Messenger", "C, Java, Perl, PHP, Python, Ruby", "Linux, OS X, JVM", "1.0"),
    ("protocol-engine", "AMQP Protocol Engine", "C, Java, Perl, PHP, Python, Ruby", "Linux, OS X, JVM", "1.0"),
    )

component_rows = list()

for key, name, languages, platforms, amqp_versions in component_records:
    link = "[{}](@site-url@/components/{}/index.html)".format(name, key)
    args = link, languages, platforms, amqp_versions
    component_rows.append("|| {} || {} || {} || {} ||".format(*args))

components = "\n  ".join(component_rows)

jql = "project = PROTON AND fixVersion = '{}' ORDER BY priority DESC".format(version)
issues_url = "https://issues.apache.org/jira/issues/?jql={}".format(urllib.quote_plus(jql))

template = \
"""
;;
;; Licensed to the Apache Software Foundation (ASF) under one
;; or more contributor license agreements.  See the NOTICE file
;; distributed with this work for additional information
;; regarding copyright ownership.  The ASF licenses this file
;; to you under the Apache License, Version 2.0 (the
;; "License"); you may not use this file except in compliance
;; with the License.  You may obtain a copy of the License at
;; 
;;   http://www.apache.org/licenses/LICENSE-2.0
;; 
;; Unless required by applicable law or agreed to in writing,
;; software distributed under the License is distributed on an
;; "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
;; KIND, either express or implied.  See the License for the
;; specific language governing permissions and limitations
;; under the License.
;;

# Qpid Proton {version}

Proton is a high-performance, lightweight messaging library. More
about [Qpid
Proton](file:///home/jross/transom/output/proton/index.html).

;; - [Release notes](release-notes.html)

## Downloads

It's important to [verify the
integrity](@site-url@/download.html#verify-what-you-download) of the
files you download.

  || *Content* || *Download* || *Signature* ||
  {downloads}

## Components

  || *Component* || *Languages* || *Platforms* || *AMQP versions* ||
  {components}

## Documentation

### Installation

 - [Installing Qpid Proton](http://svn.apache.org/repos/asf/qpid/proton/tags/{version}/README)

### AMQP Messenger

 - [C examples](messenger/c/examples/index.html)
 - [Perl examples](messenger/perl/examples/index.html)
 - [PHP examples](messenger/php/examples/index.html)
 - [Python API reference](messenger/python/api/proton.Messenger-class.html)
 - [Python examples](messenger/python/examples/index.html)
 - [Ruby examples](messenger/ruby/examples/index.html)

### AMQP Protocol Engine

 - [Python API reference](messenger/python/api/index.html)

## More information

 - [All release artefacts](http://www.apache.org/dyn/closer.cgi/qpid/proton/{version})
 - [Resolved issues in JIRA]({issues_url})
 - [Source repository branch](http://svn.apache.org/repos/asf/qpid/proton/branches/{version})
 - [Source repository tag](http://svn.apache.org/repos/asf/qpid/proton/tags/{version})
"""

output = template.format(**locals())
output = output.strip()

print output
