#!/usr/bin/python
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

import os, string, sys, urllib

version = sys.argv[1]
version = float(version)

devel_version = version - 0.01

version = "{:0.2f}".format(version)
devel_version = "{:0.2f}".format(devel_version)

download_records = (
    ("qpid-{}.tar.gz", "Full source"),
    ("qpid-cpp-{}.tar.gz", "C++ broker, Qpid Messaging API (C++, bindings)"),
    ("qpid-tools-{}.tar.gz", "C++ broker command-line tools"),
    ("qpid-java-broker-{}.tar.gz", "Java broker, Qpid JCA"),
    ("qpid-java-client-{}.tar.gz", "Qpid JMS (AMQP 0-10, 0-91, 0-9, 0-8)"),
    ("qpid-java-amqp-1-0-client-jms-{}.tar.gz", "Qpid JMS (AMQP 1.0)"),
    ("qpid-python-{}.tar.gz", "Qpid Messaging API (Python)"),
    ("qpid-wcf-{}.zip", "Qpid WCF"),
    ("qpid-qmf-{}.tar.gz", "QMF"),
    )

download_rows = list()

for artifact, summary in download_records:
    artifact = artifact.format(version)
    artifact_url = "http://www.apache.org/dyn/closer.cgi/qpid/{}/{}".format(version, artifact)
    sig_url = "http://www.apache.org/dist/qpid/{}/{}.asc".format(version, artifact)

    args = summary, artifact, artifact_url, sig_url
    row = "|| {} || [{}]({}) || [PGP]({}) ||".format(*args)

    download_rows.append(row)

downloads = "\n  ".join(download_rows)

component_records = (
    ("cpp-broker", "C++ broker", "C++", "Linux, Windows", "1.0, 0-10"),
    ("cpp-broker-tools", "C++ broker command-line tools", "-", "Linux", "0-10"),
    ("java-broker", "Java broker", "Java", "JVM", "1.0, 0-10, 0-91, 0-9, 0-8"),
    ("qpid-jca", "Qpid JCA", "Java", "JVM", "0-10"),
    ("qpid-jms", "Qpid JMS", "Java", "JVM", "1.0, 0-10, 0-91, 0-9, 0-8"),
    ("messaging-api", "Qpid Messaging API", "C++, Perl, Python, Ruby, .NET", "Linux, Windows", "1.0, 0-10"),
    ("qpid-wcf", "Qpid WCF", "C#", "Windows", "0-10"),
    ("qmf", "QMF", "C++, Python", "Linux", "0-10"),
    )

component_rows = list()

for key, name, languages, platforms, amqp_versions in component_records:
    link = "[{}](@site-url@/components/{}/index.html)".format(name, key)
    args = link, languages, platforms, amqp_versions
    component_rows.append("|| {} || {} || {} || {} ||".format(*args))

components = "\n  ".join(component_rows)

args = devel_version, version
jql = "project = QPID AND fixVersion in ('{}', '{}') ORDER BY priority DESC".format(*args)
issues_url = "https://issues.apache.org/jira/issues/?jql={}".format(urllib.quote_plus(jql))

template = \
"""
;;
;; Licensed to the Apache Software Foundation (ASF) under one
;; or more contributor license agreements.  See the NOTICE file
;; distributed with this work for additional information
;; regarding copyright ownership.  The ASF licenses this file
;; to you under the Apache License, Version 2.0 (the
;; "License"); you may not use this file except in compliance
;; with the License.  You may obtain a copy of the License at
;; 
;;   http://www.apache.org/licenses/LICENSE-2.0
;; 
;; Unless required by applicable law or agreed to in writing,
;; software distributed under the License is distributed on an
;; "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
;; KIND, either express or implied.  See the License for the
;; specific language governing permissions and limitations
;; under the License.
;;

# Qpid {version}

Qpid is a cross-platform AMQP messaging system.  It provides message
brokers written in C++ and Java, and clients for C++, C#, JMS, Perl,
Python, and Ruby.  More about [Qpid](@site-url@/index.html).

## Changes

 - [Release notes](release-notes.html)

## Downloads

It's important to [verify the
integrity](@site-url@/download.html#verify-what-you-download) of the
files you download.

  || *Content* || *Download* || *Signature* ||
  {downloads}

Java artefacts are released as compiled bytecode.  Source code is
available in the full source artefact.

## Components

  || *Component* || *Languages* || *Platforms* || *AMQP versions* ||
  {components}

## Documentation

<div class="two-column" markdown="1">
<div class="column" markdown="1">

### Books

 - [Programming in Apache Qpid](programming/book/index.html) ([PDF](programming/programming-book.pdf))
 - [C++ broker book](cpp-broker/book/index.html) ([PDF](cpp-broker/cpp-broker-book.pdf))
 - [Java broker book](java-broker/book/index.html) ([PDF](java-broker/java-broker-book.pdf))

### Installation guides

 - [Installing and Using Qpid Java](https://cwiki.apache.org/qpid/getting-started-guide.html)
 - [Installing Qpid C++](http://svn.apache.org/repos/asf/qpid/tags/{version}/qpid/cpp/INSTALL)
 - [Installing Qpid JCA](http://svn.apache.org/repos/asf/qpid/tags/{version}/qpid/java/jca/README.txt)
 - [Installing Qpid Python](http://svn.apache.org/repos/asf/qpid/tags/{version}/qpid/python/README.txt)
 - [Installing Qpid WCF](http://svn.apache.org/repos/asf/qpid/tags/{version}/qpid/wcf/ReadMe.txt)

</div>
<div class="column" markdown="1">

### API reference

 - [C++ Messaging API](messaging-api/cpp/api/index.html)
 - [Python Messaging API](messaging-api/python/api/index.html)
 - [Ruby Messaging API](messaging-api/ruby/api/index.html)
 - [.NET Messaging API](messaging-api/dotnet/api/index.html)

### Examples

 - [Qpid JCA](http://svn.apache.org/repos/asf/qpid/tags/{version}/qpid/java/jca/example/)
 - [Qpid JMS](qpid-jms/examples/index.html)
 - [C++ Messaging API](messaging-api/cpp/examples/index.html)
 - [Python Messaging API](messaging-api/python/examples/index.html)
 - [Ruby Messaging API](messaging-api/ruby/examples/index.html)
 - [.NET Messaging API](messaging-api/dotnet/examples/index.html)

</div>
</div>

## More information

 - [All release artefacts](http://www.apache.org/dyn/closer.cgi/qpid/{version})
 - [Resolved issues in JIRA]({issues_url})
 - [Source repository branch](http://svn.apache.org/repos/asf/qpid/branches/{version})
 - [Source repository tag](http://svn.apache.org/repos/asf/qpid/tags/{version})
"""

output = template.format(**locals())
output = output.strip()

print output
