#!/usr/bin/python
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

from transom.generate import *

template = \
"""
;;
;; Licensed to the Apache Software Foundation (ASF) under one
;; or more contributor license agreements.  See the NOTICE file
;; distributed with this work for additional information
;; regarding copyright ownership.  The ASF licenses this file
;; to you under the Apache License, Version 2.0 (the
;; "License"); you may not use this file except in compliance
;; with the License.  You may obtain a copy of the License at
;; 
;;   http://www.apache.org/licenses/LICENSE-2.0
;; 
;; Unless required by applicable law or agreed to in writing,
;; software distributed under the License is distributed on an
;; "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
;; KIND, either express or implied.  See the License for the
;; specific language governing permissions and limitations
;; under the License.
;;

# Qpid Proton {release} Release Notes

Proton is a high-performance, lightweight messaging library. More
about [Qpid
Proton](file:///home/jross/transom/output/proton/index.html).

For more information about this release, including download links and
documentation, see the [release overview](index.html).

{release_notes}
"""

def gen_release_notes(release, release_dir):
    output_path = join(release_dir, "release-notes.md")

    release_notes = render_release_notes("proton", release)

    output = template.format(**locals())
    output = output.strip()

    write(output_path, output)

if len(sys.argv) != 3:
    sys.exit("Usage: script RELEASE RELEASE-DIR")

release = sys.argv[1]
release_dir = sys.argv[2]

gen_release_notes(release, release_dir)
