#!/usr/bin/python
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

import sys, os, urllib, string

version = sys.argv[1]

component_records = (
    ("AMQP Messenger", "messenger/index.html", "", "Linux, OS X, JVM", "1.0"),
    ("AMQP Protocol Engine", "protocol-engine/index.html", "", "Linux, OS X, JVM", "1.0"),
    )

component_rows = list()

for name, url, languages, platforms, amqp_versions in component_records:
    url = "@site-url@/components/%s" % url

    args = name, url, platforms, amqp_versions
    component_rows.append("|| [%s](%s) || %s || %s ||" % args)

components = "\n  ".join(component_rows)

download_records = (
    ("C, Perl, PHP, Python, and Ruby", "qpid-proton-c-%s.tar.gz"),
    ("Java", "qpid-proton-j-%s.tar.gz"),
    )

download_rows = list()

for summary, artifact in download_records:
    artifact = artifact % version
    artifact_url = "http://www.apache.org/dyn/closer.cgi/qpid/proton/%s/%s" % (version, artifact)
    sig_url = "http://www.apache.org/dist/qpid/proton/%s/%s.asc" % (version, artifact)

    args = summary, artifact, artifact_url, sig_url
    row = "|| %s || [%s](%s) || [PGP](%s) ||" % args

    download_rows.append(row)

downloads = "\n  ".join(download_rows)

jql = "project = PROTON AND fixVersion = '%s' ORDER BY priority DESC" % version
issues_url = "https://issues.apache.org/jira/issues/?jql=%s" % urllib.quote_plus(jql)

template_string = \
"""
# Qpid Proton $version

Proton is a high-performance, lightweight messaging library. More
about [Qpid
Proton](file:///home/jross/transom/output/proton/index.html).

;; - [Release notes](release-notes.html)

## Components

  || *Component* || *Platforms* || *AMQP versions* ||
  $components

## Downloads

It's important to [verify the
integrity](@site-url@/releases/index.html#verify-what-you-download) of
the files you download.

  || *Content* || *Download* || *Signature* ||
  $downloads

## Documentation

 - [Installing Qpid Proton C](http://svn.apache.org/repos/asf/qpid/proton/branches/${version}/proton-c/README)
 - [Installing Qpid Proton Java](http://svn.apache.org/repos/asf/qpid/proton/branches/${version}/proton-j/proton/README)

## More information

 - [All release artifacts](http://www.apache.org/dyn/closer.cgi/qpid/proton/${version})
 - [Resolved issues in JIRA]($issues_url)
 - [Source repository branch](http://svn.apache.org/repos/asf/qpid/proton/branches/${version})
;; - [Source repository tag](http://svn.apache.org/repos/asf/qpid/proton/tags/${version})
"""

template = string.Template(template_string)

output = template.substitute(locals())
output = output.strip()

print output
